spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    name: employeeManagement
    password: root
    username: root
    url: jdbc:h2:mem:employeeManagement
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.yandex.ru
    port: 465
    username: kirstradz11@yandex.ru
    password: teshegeptebgkurl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
        transport:
          protocol: smtps
    protocol: smtps

vacation-payment-calculator:
  url: http://localhost:8080/calculate
server:
  port: 8081